In [4]:
import numpy as np

In [2]:
one_dim=np.array([1,2,3.4,5])
print(one_dim)

[1.  2.  3.4 5. ]


In [6]:
two_dim=np.array([[1,2], [34,5], [4.32,32]])
print(two_dim)

[[ 1.    2.  ]
 [34.    5.  ]
 [ 4.32 32.  ]]


In [9]:
# all zeros
all_zeros = np.zeros((3, 3))
print(all_zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [10]:
#all ones
all_ones=np.ones((3,5))
print(all_ones)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [12]:
sequence=np.arange(3,12)
print(sequence)

[ 3  4  5  6  7  8  9 10 11]


In [13]:
#Random numbers in array
random1=np.random.randint(low=1, high=100, size=(6,))
print(random1)

[68 20 84 63 80 95]


In [6]:
random_float=np.random.random(6,)
print(random_float)

[0.02380744 0.23469257 0.29240736 0.48141201 0.62933065 0.51990008]


In [7]:
#adding matrices
random_add=random_float+3.1
print(random_add)

[3.12380744 3.33469257 3.39240736 3.58141201 3.72933065 3.61990008]


In [9]:
#multiply
random_multi=random1*3
print(random_multi)

[144 111  24 282  45 240]


In [10]:
#Task 1: Create a Linear Dataset
#Your goal is to create a simple dataset consisting of a single feature and a label as follows:

#Assign a sequence of integers from 6 to 20 (inclusive) to a NumPy array named feature.
#Assign 15 values to a NumPy array named label such that: label = (3)(feature) + 4

feature=np.arange(1,16)
print(feature)
label=(3*feature)+4
print(label)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[ 7 10 13 16 19 22 25 28 31 34 37 40 43 46 49]


In [20]:
#Task 2: Add Some Noise to the Dataset
#To make your dataset a little more realistic, insert a little random noise into each element of the label array you already created. To be more precise, modify each value assigned to label by adding a different random floating-point value between -2 and +2.

#Don't rely on broadcasting. Instead, create a noise array having the same dimension as label.
noise=np.random.random([15]*4)-2
print(noise)
label=label+noise
print(label)

[[[[-1.6642141  -1.04883353 -1.29638363 ... -1.7145927  -1.52961285
    -1.14866491]
   [-1.57411203 -1.12028978 -1.8036777  ... -1.90090755 -1.71218923
    -1.0310274 ]
   [-1.33615301 -1.53886029 -1.95425938 ... -1.65340937 -1.66609025
    -1.13074895]
   ...
   [-1.90120994 -1.29120205 -1.99682361 ... -1.57331196 -1.18352213
    -1.28047402]
   [-1.5565738  -1.11842668 -1.28985776 ... -1.16583828 -1.29072351
    -1.57911842]
   [-1.76204512 -1.59182259 -1.19660072 ... -1.73417739 -1.53744873
    -1.11308902]]

  [[-1.31988113 -1.16078786 -1.20382114 ... -1.87091972 -1.93765757
    -1.79921038]
   [-1.02103175 -1.67178046 -1.93748224 ... -1.56529615 -1.42209953
    -1.52098224]
   [-1.61211442 -1.16975552 -1.96559409 ... -1.90284878 -1.79398633
    -1.20905044]
   ...
   [-1.95443845 -1.22215699 -1.84854834 ... -1.10414727 -1.98621159
    -1.15045477]
   [-1.61690603 -1.92690989 -1.71396464 ... -1.80820855 -1.34000155
    -1.98527287]
   [-1.0736382  -1.85458073 -1.4960357  ... -1.24