In [1]:
import numpy as np

In [2]:
one_dim=np.array([1,2,3.4,5])
print(one_dim)

[1.  2.  3.4 5. ]


In [3]:
two_dim=np.array([[1,2], [34,5], [4.32,32]])
print(two_dim)

[[ 1.    2.  ]
 [34.    5.  ]
 [ 4.32 32.  ]]


In [4]:
# all zeros
all_zeros = np.zeros((3, 3))
print(all_zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [5]:
#all ones
all_ones=np.ones((3,5))
print(all_ones)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [6]:
sequence=np.arange(3,12)
print(sequence)

[ 3  4  5  6  7  8  9 10 11]


In [7]:
#Random numbers in array
random1=np.random.randint(low=1, high=100, size=(6,))
print(random1)

[ 6 86 37 27 83  4]


In [8]:
random_float=np.random.random(6,)
print(random_float)

[0.89602515 0.97304755 0.7526845  0.60538711 0.91782176 0.61878815]


In [9]:
#adding matrices
random_add=random_float+3.1
print(random_add)

[3.99602515 4.07304755 3.8526845  3.70538711 4.01782176 3.71878815]


In [10]:
#multiply
random_multi=random1*3
print(random_multi)

[ 18 258 111  81 249  12]


In [11]:
#Task 1: Create a Linear Dataset
#Your goal is to create a simple dataset consisting of a single feature and a label as follows:

#Assign a sequence of integers from 6 to 20 (inclusive) to a NumPy array named feature.
#Assign 15 values to a NumPy array named label such that: label = (3)(feature) + 4

feature=np.arange(1,16)
print(feature)
label=(3*feature)+4
print(label)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[ 7 10 13 16 19 22 25 28 31 34 37 40 43 46 49]


In [12]:
#Task 2: Add Some Noise to the Dataset
#To make your dataset a little more realistic, insert a little random noise into each element of the label array you already created. To be more precise, modify each value assigned to label by adding a different random floating-point value between -2 and +2.

#Don't rely on broadcasting. Instead, create a noise array having the same dimension as label.
noise=np.random.random([15]*4)-2
print(noise)
label=label+noise
print(label)

[[[[-1.59611641 -1.95269148 -1.61564786 ... -1.72301808 -1.93848199
    -1.30624312]
   [-1.63255919 -1.67936489 -1.26133011 ... -1.44841607 -1.27233142
    -1.23539248]
   [-1.21850859 -1.87227086 -1.52018448 ... -1.15102818 -1.17354001
    -1.64021622]
   ...
   [-1.84049129 -1.54157919 -1.00532759 ... -1.49958245 -1.27777305
    -1.79882709]
   [-1.56978157 -1.84684001 -1.52368316 ... -1.81651716 -1.58330392
    -1.47717614]
   [-1.5685492  -1.54192233 -1.17376738 ... -1.22553008 -1.60777482
    -1.06584396]]

  [[-1.46678227 -1.74010353 -1.87265623 ... -1.28438228 -1.76790714
    -1.7097591 ]
   [-1.69098114 -1.03622816 -1.78124961 ... -1.1372349  -1.04440007
    -1.38426321]
   [-1.46370371 -1.14194069 -1.32464632 ... -1.74193901 -1.16109654
    -1.67043009]
   ...
   [-1.07495391 -1.22041894 -1.25711704 ... -1.58560664 -1.0033364
    -1.50801428]
   [-1.84012454 -1.40911523 -1.30032667 ... -1.89765039 -1.36530287
    -1.52578741]
   [-1.52465033 -1.75443768 -1.75662798 ... -1.329