In [1]:
import numpy as np

In [2]:
one_dim=np.array([1,2,3.4,5])
print(one_dim)

[1.  2.  3.4 5. ]


In [6]:
two_dim=np.array([[1,2], [34,5], [4.32,32]])
print(two_dim)

[[ 1.    2.  ]
 [34.    5.  ]
 [ 4.32 32.  ]]


In [9]:
# all zeros
all_zeros = np.zeros((3, 3))
print(all_zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [10]:
#all ones
all_ones=np.ones((3,5))
print(all_ones)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [12]:
sequence=np.arange(3,12)
print(sequence)

[ 3  4  5  6  7  8  9 10 11]


In [14]:
#Random numbers in array
random=np.random.randint(low=1, high=100, size=(6,))
print(random)

[87 40 86 96 90  9]
